### ISSUE TITLE
Phone/Mobile Field - Validate phone number bug

### ISSUE THREAD

**Issue by webdost** [fluentform/fluentform#289]
Hi,

When entering the phone number with the validity control, there is a bug. The country flag hides the first characters of the number.

I tested on different browsers and also in private browsing.

I am sending you an example as an attachment.
![2023-04-14 10_14_26](https://user-images.githubusercontent.com/130752933/232017927-815eab55-7f18-4791-8056-ea70324947ba.png)

Thanks for your help
Stéphane

**Comment by webdost** [comment]
I answer my problem.
Which was corrected by the support in a remarkable way and ultra quickly.

It was a conflict between my page builder "Elementor", which had overwritten the display parameters.

It was enough to add a custom CSS code on the modules where the form appears.

Here is the code: 

```css
.iti--allow-dropdown input, .iti--allow-dropdown input[type=tel], .iti--allow-dropdown input[type=text], .iti--separate-dial-code input, .iti--separate-dial-code input[type=tel], .iti--separate-dial-code input[type=text] {
margin-left: 47px !important;
}
```
